baseURL = "/"
title = "Si Tan"
author = "Tanio"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
# DO NOT REMOVE THIS
theme = "harbor"

[Author]
  name = "Tanio"

[permalinks]
	post = "/post/:filename/"
	page = "/:filename/"

[outputs]
    section = ["JSON", "HTML"]

[[params.nav]]
  identifier = "about"
  name = "About"
  icon = "fas fa-user fa-lg"
  url = "/about/"
  weight = 3

[[params.nav]]
  identifier = "tags"
  name = "Tags"
  icon = "fas fa-tag fa-lg"
  url = "/tags/"
  weight = 3

[[params.nav]]
  identifier = "search"
  name = "Search"
  icon = "fas fa-search fa-lg"
  url = "/search/"
  weight = 3

[[params.social]]
  name= "facebook"
  url="https://facebook.com/19t4n"
  icon="fab fa-facebook"

[params]
  mainSections = ["post"]
  favicon = "favicon.ico"

  [params.logo]
    url = "icon.png"
    width = 50
    height = 50
    alt = "Logo"
